version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@1.3

jobs:
  replay-standard:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - kubernetes/install-kubectl:
          kubectl-version: "1.23.3"
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          # install-kubectl: true
      - run:
          command: |
            tools/deploy-replays.sh standard
  replay-performance:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - kubernetes/install-kubectl:
          kubectl-version: "1.23.3"
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          # install-kubectl: true
      - run:
          command: |
            tools/deploy-replays.sh performance

workflows:
  deployment:
    jobs:
      - replay-standard:
          context:
            - demo 
          cluster-name: staging-decoy
      - replay-performance:
          context:
            - demo 
          cluster-name: staging-decoy
