version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.1.2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          aws-profile: demo 
          aws-region: us-east-1 
          cluster-name: staging-decoy 
          
      - checkout
      - run: kubectl get pods

workflows:
  example-workflow:
    jobs:
      - example-job
